"""initial schema: pgvector extension + all tables + indexes

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-23

Hand-written (not autogenerated) so that extensions, the pgvector column,
HNSW index, CHECK constraints, and the deferred decisions.chosen_option_id FK
are all created in the correct order.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TZ = sa.DateTime(timezone=True)


def _ts_columns() -> list[sa.Column]:
    return [
        sa.Column("created_at", TZ, server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", TZ, server_default=sa.text("now()"), nullable=False),
    ]


def upgrade() -> None:
    # --- Extensions --------------------------------------------------------
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    gen_uuid = sa.text("gen_random_uuid()")

    # --- tenants -----------------------------------------------------------
    op.create_table(
        "tenants",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=gen_uuid, primary_key=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("plan_tier", sa.Text(), server_default="free", nullable=False),
        sa.Column("task_quota_month", sa.Integer(), server_default="50", nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        *_ts_columns(),
        sa.CheckConstraint(
            "plan_tier IN ('free','solo_starter','solo_pro','studio')",
            name="ck_tenants_plan_tier",
        ),
        sa.CheckConstraint(
            "status IN ('active','suspended','closed')", name="ck_tenants_status"
        ),
    )

    # --- users -------------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=gen_uuid, primary_key=True),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("mfa_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("sso_subject", sa.Text(), nullable=True),
        sa.Column("last_login_at", TZ, nullable=True),
        sa.Column("locale", sa.Text(), server_default="en", nullable=False),
        sa.Column("timezone", sa.Text(), server_default="UTC", nullable=False),
        sa.Column(
            "default_autonomy_profile", sa.Text(), server_default="ask_first", nullable=False
        ),
        sa.Column("created_at", TZ, server_default=sa.text("now()"), nullable=False),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )

    # --- memberships -------------------------------------------------------
    op.create_table(
        "memberships",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=gen_uuid, primary_key=True),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("role", sa.Text(), server_default="owner", nullable=False),
        sa.Column("invited_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        *_ts_columns(),
        sa.UniqueConstraint("tenant_id", "user_id", name="uq_membership_tenant_user"),
    )

    # --- businesses --------------------------------------------------------
    op.create_table(
        "businesses",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=gen_uuid, primary_key=True),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("model_template", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("stage", sa.Text(), server_default="ideation", nullable=False),
        sa.Column("autonomy_profile", sa.Text(), server_default="ask_first", nullable=False),
        sa.Column("guardrails", postgresql.JSONB(), server_default="{}", nullable=False),
        sa.Column("brand_voice", sa.Text(), nullable=True),
        sa.Column("deleted_at", TZ, nullable=True),
        *_ts_columns(),
        sa.CheckConstraint(
            "stage IN ('ideation','validate','build','launch','grow','scale','exit_prep','exit')",
            name="ck_businesses_stage",
        ),
        sa.CheckConstraint(
            "autonomy_profile IN ('ask_first','guided','autonomous_within_limits')",
            name="ck_businesses_autonomy",
        ),
    )
    op.create_index(
        "idx_businesses_tenant",
        "businesses",
        ["tenant_id"],
        postgresql_where=sa.text("deleted_at IS NULL"),
    )

    # --- goals -------------------------------------------------------------
    op.create_table(
        "goals",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=gen_uuid, primary_key=True),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "business_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("businesses.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("metric", sa.Text(), nullable=True),
        sa.Column("target_value", sa.Numeric(), nullable=True),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("created_at", TZ, server_default=sa.text("now()"), nullable=False),
    )
    op.create_index("idx_goals_business", "goals", ["business_id"])

    # --- okrs --------------------------------------------------------------
    op.create_table(
        "okrs",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=gen_uuid, primary_key=True),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "goal_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("goals.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("key_result", sa.Text(), nullable=False),
        sa.Column("target_value", sa.Numeric(), nullable=True),
        sa.Column("current_value", sa.Numeric(), server_default="0", nullable=True),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("status", sa.Text(), server_default="on_track", nullable=False),
        sa.Column("created_at", TZ, server_default=sa.text("now()"), nullable=False),
    )
    op.create_index("idx_okrs_goal", "okrs", ["goal_id"])

    # --- agents (global registry) -----------------------------------------
    op.create_table(
        "agents",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=gen_uuid, primary_key=True),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("default_model", sa.Text(), server_default="claude-sonnet-4-6", nullable=False),
        sa.Column("min_tier", sa.Text(), server_default="free", nullable=False),
        sa.Column("tool_scopes", postgresql.JSONB(), server_default="{}", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        *_ts_columns(),
        sa.UniqueConstraint("key", name="uq_agents_key"),
    )

    # --- agent_runs --------------------------------------------------------
    op.create_table(
        "agent_runs",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=gen_uuid, primary_key=True),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "business_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("businesses.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "agent_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("agents.id"),
            nullable=False,
        ),
        sa.Column(
            "goal_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("goals.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("status", sa.Text(), server_default="planned", nullable=False),
        sa.Column("objective", sa.Text(), nullable=True),
        sa.Column("inputs", postgresql.JSONB(), server_default="{}", nullable=False),
        sa.Column("output", postgresql.JSONB(), nullable=True),
        sa.Column("progress", sa.Float(), server_default="0", nullable=False),
        sa.Column("model_used", sa.Text(), nullable=True),
        sa.Column("token_input", sa.Integer(), server_default="0", nullable=False),
        sa.Column("token_output", sa.Integer(), server_default="0", nullable=False),
        sa.Column("started_at", TZ, nullable=True),
        sa.Column("finished_at", TZ, nullable=True),
        sa.Column("created_at", TZ, server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('planned','queued','running','awaiting_approval',"
            "'succeeded','failed','cancelled')",
            name="ck_agent_runs_status",
        ),
    )
    op.create_index("idx_agent_runs_business", "agent_runs", ["business_id", "status"])

    # --- tasks -------------------------------------------------------------
    op.create_table(
        "tasks",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=gen_uuid, primary_key=True),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "agent_run_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("agent_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "parent_task_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tasks.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("agent_key", sa.Text(), nullable=True),
        sa.Column("risk_level", sa.Text(), server_default="low", nullable=False),
        sa.Column("payload", postgresql.JSONB(), server_default="{}", nullable=False),
        sa.Column("result", postgresql.JSONB(), nullable=True),
        sa.Column("status", sa.Text(), server_default="queued", nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("attempts", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("next_retry_at", TZ, nullable=True),
        sa.Column("approved_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("approved_at", TZ, nullable=True),
        sa.Column("created_at", TZ, server_default=sa.text("now()"), nullable=False),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_task_tenant_idempotency"),
    )
    op.create_index("idx_tasks_ready", "tasks", ["status", "next_retry_at"])
    op.create_index("idx_tasks_run", "tasks", ["agent_run_id"])

    # --- decisions ---------------------------------------------------------
    op.create_table(
        "decisions",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=gen_uuid, primary_key=True),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "business_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("businesses.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("decision_type", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("ai_recommendation", sa.Text(), nullable=True),
        sa.Column("overall_call", sa.Text(), nullable=True),
        sa.Column("chosen_option_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("status", sa.Text(), server_default="open", nullable=False),
        sa.Column("decided_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("decided_at", TZ, nullable=True),
        sa.Column("created_at", TZ, server_default=sa.text("now()"), nullable=False),
    )
    op.create_index("idx_decisions_business", "decisions", ["business_id", "status"])

    # --- decision_options --------------------------------------------------
    op.create_table(
        "decision_options",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=gen_uuid, primary_key=True),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "decision_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("decisions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("option_name", sa.Text(), nullable=False),
        sa.Column("risk_score", sa.SmallInteger(), nullable=True),
        sa.Column("complexity_score", sa.SmallInteger(), nullable=True),
        sa.Column("potential_score", sa.SmallInteger(), nullable=True),
        sa.Column("time_to_impact", sa.Text(), nullable=True),
        sa.Column("capital_required_cents", sa.BigInteger(), nullable=True),
        sa.Column("advisor_scores", postgresql.JSONB(), server_default="{}", nullable=False),
        sa.Column("ai_justification", sa.Text(), nullable=True),
        sa.Column("is_recommended", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", TZ, server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("risk_score BETWEEN 0 AND 100", name="ck_options_risk"),
        sa.CheckConstraint("complexity_score BETWEEN 0 AND 100", name="ck_options_complexity"),
        sa.CheckConstraint("potential_score BETWEEN 0 AND 100", name="ck_options_potential"),
    )
    op.create_index("idx_options_decision", "decision_options", ["decision_id"])
    op.create_index(
        "idx_options_scores",
        "decision_options",
        [sa.text("potential_score DESC"), sa.text("risk_score ASC")],
    )

    # Deferred FK now that decision_options exists.
    op.create_foreign_key(
        "fk_decisions_chosen_option",
        "decisions",
        "decision_options",
        ["chosen_option_id"],
        ["id"],
    )

    # --- integrations ------------------------------------------------------
    op.create_table(
        "integrations",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=gen_uuid, primary_key=True),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "business_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("businesses.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="connected", nullable=False),
        sa.Column("config", postgresql.JSONB(), server_default="{}", nullable=False),
        sa.Column("connected_at", TZ, nullable=True),
        *_ts_columns(),
    )
    op.create_index("idx_integrations_business", "integrations", ["business_id"])

    # --- integration_credentials ------------------------------------------
    op.create_table(
        "integration_credentials",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=gen_uuid, primary_key=True),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "integration_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("integrations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("auth_type", sa.Text(), server_default="oauth2", nullable=False),
        sa.Column("secret_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("key_id", sa.Text(), nullable=True),
        sa.Column("access_token_expires_at", TZ, nullable=True),
        sa.Column("scopes", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("created_at", TZ, server_default=sa.text("now()"), nullable=False),
        sa.UniqueConstraint("integration_id", name="uq_integration_credential_integration"),
    )

    # --- metrics -----------------------------------------------------------
    op.create_table(
        "metrics",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=gen_uuid, primary_key=True),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "business_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("businesses.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("metric_key", sa.Text(), nullable=False),
        sa.Column("value", sa.Numeric(), nullable=False),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("recorded_at", TZ, server_default=sa.text("now()"), nullable=False),
    )
    op.create_index("idx_metrics_business_key", "metrics", ["business_id", "metric_key"])

    # --- activity_log ------------------------------------------------------
    op.create_table(
        "activity_log",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=gen_uuid, primary_key=True),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "business_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("businesses.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column("actor_type", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.Text(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("target_type", sa.Text(), nullable=True),
        sa.Column("target_id", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("meta", postgresql.JSONB(), server_default="{}", nullable=False),
        sa.Column("trace_id", sa.Text(), nullable=True),
        sa.Column("created_at", TZ, server_default=sa.text("now()"), nullable=False),
    )
    op.create_index(
        "idx_activity_business", "activity_log", ["business_id", sa.text("created_at DESC")]
    )

    # --- memory_entries (pgvector) ----------------------------------------
    op.create_table(
        "memory_entries",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=gen_uuid, primary_key=True),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "business_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("businesses.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("scope", sa.Text(), server_default="company", nullable=False),
        sa.Column("source_type", sa.Text(), nullable=True),
        sa.Column("source_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(1536), nullable=False),
        sa.Column("meta", postgresql.JSONB(), server_default="{}", nullable=False),
        sa.Column("created_at", TZ, server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "scope IN ('company','task','decision','support_kb','brand')",
            name="ck_memory_scope",
        ),
    )
    op.create_index("idx_memory_scope", "memory_entries", ["business_id", "scope"])
    op.execute(
        "CREATE INDEX idx_memory_embedding_hnsw ON memory_entries "
        "USING hnsw (embedding vector_cosine_ops)"
    )

    # --- exit_readiness ----------------------------------------------------
    op.create_table(
        "exit_readiness",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=gen_uuid, primary_key=True),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "business_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("businesses.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("overall_score", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("financials_score", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("metrics_score", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("documentation_score", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column(
            "operational_stability_score", sa.SmallInteger(), server_default="0", nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("assessed_at", TZ, server_default=sa.text("now()"), nullable=False),
        sa.UniqueConstraint("business_id", name="uq_exit_readiness_business"),
    )

    # --- documents ---------------------------------------------------------
    op.create_table(
        "documents",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=gen_uuid, primary_key=True),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "business_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("businesses.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("is_data_room", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", TZ, server_default=sa.text("now()"), nullable=False),
    )
    op.create_index("idx_documents_business", "documents", ["business_id"])


def downgrade() -> None:
    op.drop_table("documents")
    op.drop_table("exit_readiness")
    op.execute("DROP INDEX IF EXISTS idx_memory_embedding_hnsw")
    op.drop_table("memory_entries")
    op.drop_table("activity_log")
    op.drop_table("metrics")
    op.drop_table("integration_credentials")
    op.drop_table("integrations")
    op.drop_constraint("fk_decisions_chosen_option", "decisions", type_="foreignkey")
    op.drop_table("decision_options")
    op.drop_table("decisions")
    op.drop_table("tasks")
    op.drop_table("agent_runs")
    op.drop_table("agents")
    op.drop_table("okrs")
    op.drop_table("goals")
    op.drop_table("businesses")
    op.drop_table("memberships")
    op.drop_table("users")
    op.drop_table("tenants")
